# Generated by Django 5.0.6 on 2024-10-09 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={
                "verbose_name": "Fichier Uploadé",
                "verbose_name_plural": "Fichiers Uploadés",
            },
        ),
        migrations.RemoveField(
            model_name="normeparametres",
            name="id_norme",
        ),
        migrations.RemoveField(
            model_name="normeparametres",
            name="id_parametres",
        ),
        migrations.RemoveField(
            model_name="resultats",
            name="utilisateur",
        ),
        migrations.AddField(
            model_name="normeparametres",
            name="norme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="norme_parametres",
                to="website.norme",
            ),
        ),
        migrations.AddField(
            model_name="normeparametres",
            name="parametre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="norme_parametres",
                to="website.parametre",
            ),
        ),
        migrations.AddField(
            model_name="resultats",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="resultats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="parametre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="resultats",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
