# Generated by Django 5.1.1 on 2024-10-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
